modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

issueTrackerURL="https://github.com/Mani-cwaf/Ruby-Items-1.16.1-1.0.0" #optional

[[mods]] #mandatory

modId="ruby_items" #mandatory

version="1.16.1-1.0.0" #mandatory

displayName="Ruby Items" #mandatory

updateJSONURL="https://github.com/Mani-cwaf/Ruby-Items-1.16.1-1.0.0" #optional

displayURL="https://github.com/Mani-cwaf/Ruby-Items-1.16.1-1.0.0" #optional

logoFile="modlogo.png" #optional

credits="Mani_cwaf" #optional

authors="Mani_cwaf" #optional

description='''A mod that adds ruby items to Minecraft'''

[[dependencies]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
